http:
  listner: 
    host: "localhost"
    port: "8081"
    path: "/travelOnTip/{serviceType}"
    
    
db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "anusha"
  database: "hbt"
  